<?php

namespace Database\Seeders;

use App\Models\Toy;
use Illuminate\Database\Seeder;

class ToySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $toys = [
            [
                'name' => 'Vintage Star Wars Action Figure',
                'brand' => 'Kenner',
                'category' => 'Action Figures',
                'description' => 'Original 1977 Luke Skywalker action figure in excellent condition.',
                'condition' => 'Excellent',
                'purchase_price' => 45.00,
                'estimated_value' => 150.00,
                'purchase_date' => '2023-05-15',
                'manufacture_date' => '1977-01-01',
                'in_box' => false,
                'notes' => 'Found at local antique shop',
            ],
            [
                'name' => 'Barbie Dreamhouse',
                'brand' => 'Mattel',
                'category' => 'Dolls',
                'description' => '1960s Barbie Dreamhouse with original furniture pieces.',
                'condition' => 'Good',
                'purchase_price' => 120.00,
                'estimated_value' => 300.00,
                'purchase_date' => '2023-08-20',
                'manufacture_date' => '1965-01-01',
                'in_box' => true,
                'notes' => 'Complete set with most accessories',
            ],
            [
                'name' => 'Hot Wheels Redline',
                'brand' => 'Mattel',
                'category' => 'Vehicles',
                'description' => '1968 Hot Wheels Redline Custom Camaro in mint condition.',
                'condition' => 'Mint',
                'purchase_price' => 85.00,
                'estimated_value' => 250.00,
                'purchase_date' => '2023-11-10',
                'manufacture_date' => '1968-01-01',
                'in_box' => true,
                'notes' => 'Original packaging, never opened',
            ],
            [
                'name' => 'Transformers Optimus Prime G1',
                'brand' => 'Hasbro',
                'category' => 'Action Figures',
                'description' => '1984 Generation 1 Optimus Prime transformer, fully functional with all accessories.',
                'condition' => 'Excellent',
                'purchase_price' => 200.00,
                'estimated_value' => 450.00,
                'purchase_date' => '2023-06-12',
                'manufacture_date' => '1984-01-01',
                'in_box' => false,
                'notes' => 'Includes original trailer and accessories',
            ],
            [
                'name' => 'GI Joe Snake Eyes',
                'brand' => 'Hasbro',
                'category' => 'Action Figures',
                'description' => '1982 GI Joe Snake Eyes action figure with original weapons and file card.',
                'condition' => 'Good',
                'purchase_price' => 75.00,
                'estimated_value' => 180.00,
                'purchase_date' => '2023-09-05',
                'manufacture_date' => '1982-01-01',
                'in_box' => false,
                'notes' => 'Missing one small accessory',
            ],
            [
                'name' => 'Pokemon First Edition Charizard',
                'brand' => 'Wizards of the Coast',
                'category' => 'Collectibles',
                'description' => '1999 Pokemon Base Set First Edition Charizard holographic card, PSA graded.',
                'condition' => 'Mint',
                'purchase_price' => 500.00,
                'estimated_value' => 1200.00,
                'purchase_date' => '2023-07-22',
                'manufacture_date' => '1999-01-01',
                'in_box' => true,
                'notes' => 'PSA 9 grade, professionally graded and sealed',
            ],
            [
                'name' => 'Lego Star Wars Millennium Falcon',
                'brand' => 'Lego',
                'category' => 'Collectibles',
                'description' => '2007 Ultimate Collector Series Millennium Falcon set 10179, complete with instructions.',
                'condition' => 'Excellent',
                'purchase_price' => 350.00,
                'estimated_value' => 800.00,
                'purchase_date' => '2023-10-15',
                'manufacture_date' => '2007-01-01',
                'in_box' => true,
                'notes' => 'All pieces accounted for, original box',
            ],
            [
                'name' => 'Cabbage Patch Kid',
                'brand' => 'Coleco',
                'category' => 'Dolls',
                'description' => '1983 Original Cabbage Patch Kid with adoption papers and birth certificate.',
                'condition' => 'Good',
                'purchase_price' => 60.00,
                'estimated_value' => 150.00,
                'purchase_date' => '2023-08-30',
                'manufacture_date' => '1983-01-01',
                'in_box' => false,
                'notes' => 'Original clothing, minor wear',
            ],
            [
                'name' => 'Matchbox Superfast',
                'brand' => 'Matchbox',
                'category' => 'Vehicles',
                'description' => '1970s Matchbox Superfast series #75 Mercedes 350SL in original packaging.',
                'condition' => 'Mint',
                'purchase_price' => 40.00,
                'estimated_value' => 120.00,
                'purchase_date' => '2023-11-25',
                'manufacture_date' => '1975-01-01',
                'in_box' => true,
                'notes' => 'Never removed from blister pack',
            ],
            [
                'name' => 'My Little Pony First Generation',
                'brand' => 'Hasbro',
                'category' => 'Plush Toys',
                'description' => '1983 My Little Pony "Applejack" first generation with original brush.',
                'condition' => 'Excellent',
                'purchase_price' => 35.00,
                'estimated_value' => 90.00,
                'purchase_date' => '2023-09-18',
                'manufacture_date' => '1983-01-01',
                'in_box' => false,
                'notes' => 'Hair in good condition, original accessories',
            ],
            [
                'name' => 'He-Man Masters of the Universe',
                'brand' => 'Mattel',
                'category' => 'Action Figures',
                'description' => '1982 He-Man action figure with Power Sword and Battle Armor.',
                'condition' => 'Good',
                'purchase_price' => 55.00,
                'estimated_value' => 140.00,
                'purchase_date' => '2023-07-08',
                'manufacture_date' => '1982-01-01',
                'in_box' => false,
                'notes' => 'All accessories included, minor paint wear',
            ],
            [
                'name' => 'Beanie Baby Princess Diana',
                'brand' => 'Ty',
                'category' => 'Plush Toys',
                'description' => '1997 Ty Beanie Baby Princess Diana bear with original tag protector.',
                'condition' => 'Mint',
                'purchase_price' => 25.00,
                'estimated_value' => 200.00,
                'purchase_date' => '2023-10-02',
                'manufacture_date' => '1997-01-01',
                'in_box' => true,
                'notes' => 'Mint condition with original tag, never removed from box',
            ],
            [
                'name' => 'Nintendo Game Boy',
                'brand' => 'Nintendo',
                'category' => 'Collectibles',
                'description' => '1989 Original Game Boy with original box, manuals, and Tetris game.',
                'condition' => 'Excellent',
                'purchase_price' => 150.00,
                'estimated_value' => 350.00,
                'purchase_date' => '2023-06-20',
                'manufacture_date' => '1989-01-01',
                'in_box' => true,
                'notes' => 'Fully functional, all original packaging',
            ],
        ];

        foreach ($toys as $toy) {
            Toy::create($toy);
        }
    }
}

